callback({
    "result": 0,
    "data": {
        "district_data": {
            "title": "位置",
            "city": "深圳市",
            "district": ["南山区", "宝安区", "盐田区", "福田区", "罗湖区", "龙岗区"]
        },
        "education_data": {
            "title": "学历",
            "education": ["博士", "硕士", "本科", "专科", "中学", "小学", "其它"]
        },
        "grade_data":{
            "title": "年级",
            "data":["2008", "2007", "2006"]
        },
        "college_data": [{
            "collegeid": "1",
            "college": "自动化学院",
            "professions": [{
                "professionid": "1",
                "profession": "自动化（创新班）"
            }, {
                "professionid": "2",
                "profession": "自动化（卓越工程师班）"
            }, {
                "professionid": "3",
                "profession": "自动化"
            }, {
                "professionid": "4",
                "profession": "电气工程及其自动化(电气与电子技术方向）"
            }, {
                "professionid": "5",
                "profession": "电气工程及其自动化(电力系统自动化方向)"
            }, {
                "professionid": "6",
                "profession": "物联网工程"
            }, {
                "professionid": "7",
                "profession": "电子信息科学与技术"
            }]
        }, {
            "collegeid": "2",
            "college": "机电工程学院",
            "professions": [{
                "professionid": "8",
                "profession": "机械设计制造及其自动化（创新班）"
            }, {
                "professionid": "9",
                "profession": "机械设计制造及其自动化（卓越工程师班）"
            }, {
                "professionid": "10",
                "profession": "机械设计制造及其自动化（机械电子工程方向）"
            }, {
                "professionid": "11",
                "profession": "机械设计制造及其自动化（微电子制造装备及自动化方向）"
            }, {
                "professionid": "12",
                "profession": "车辆工程"
            }, {
                "professionid": "13",
                "profession": "工业工程"
            }, {
                "professionid": "14",
                "profession": "包装工程"
            }, {
                "professionid": "15",
                "profession": "数字媒体技术"
            }]
        }, {
            "collegeid": "3",
            "college": "轻工化工学院",
            "professions": [{
                "professionid": "16",
                "profession": "化工与制药类(创新班)"
            }, {
                "professionid": "17",
                "profession": "化学工程与工艺（卓越工程师班）"
            }, {
                "professionid": "18",
                "profession": "化学工程与工艺"
            }, {
                "professionid": "19",
                "profession": "应用化学"
            }, {
                "professionid": "20",
                "profession": "食品科学与工程"
            }, {
                "professionid": "21",
                "profession": "制药工程"
            }, {
                "professionid": "22",
                "profession": "生物工程(生物化工、微生物工程方向)"
            }]
        }, {
            "collegeid": "4",
            "college": "信息工程学院",
            "professions": [{
                "professionid": "23",
                "profession": "信息工程（卓越工程师班）"
            }, {
                "professionid": "24",
                "profession": ""
            }, {
                "professionid": "25",
                "profession": "信息工程（电子信息工程方向）"
            }, {
                "professionid": "26",
                "profession": "信息工程（应用电子技术方向）"
            }, {
                "professionid": "27",
                "profession": "通信工程"
            }, {
                "professionid": "28",
                "profession": "测控技术与仪器（计算机测控技术方向）"
            }, {
                "professionid": "29",
                "profession": "测控技术与仪器（光机电一体化方向）"
            }]
        }, {
            "collegeid": "5",
            "college": "土木与交通工程学院",
            "professions": [{
                "professionid": "30",
                "profession": "土木工程"
            }, {
                "professionid": "31",
                "profession": "道路桥梁与渡河工程"
            }, {
                "professionid": "32",
                "profession": "工程管理"
            }, {
                "professionid": "33",
                "profession": "给排水科学与工程"
            }, {
                "professionid": "34",
                "profession": "建筑环境与能源应用工程"
            }, {
                "professionid": "35",
                "profession": "交通运输"
            }, {
                "professionid": "36",
                "profession": "测绘工程"
            }, {
                "professionid": "37",
                "profession": "城市地下空间工程"
            }]
        }, {
            "collegeid": "6",
            "college": "管理学院",
            "professions": [{
                "professionid": "38",
                "profession": "管理科学(金融理财方向)"
            }, {
                "professionid": "39",
                "profession": "物流管理"
            }, {
                "professionid": "40",
                "profession": "信息管理与信息系统"
            }, {
                "professionid": "41",
                "profession": "电子商务"
            }, {
                "professionid": "42",
                "profession": "工商管理"
            }, {
                "professionid": "43",
                "profession": "市场营销"
            }, {
                "professionid": "44",
                "profession": "人力资源管理"
            }, {
                "professionid": "45",
                "profession": "财务管理"
            }, {
                "professionid": "46",
                "profession": "会计学"
            }, {
                "professionid": "47",
                "profession": "土地资源管理（国土资源与房地产开发方向）"
            }, {
                "professionid": "48",
                "profession": "旅游管理"
            }]
        }, {
            "collegeid": "7",
            "college": "计算机学院",
            "professions": [{
                "professionid": "49",
                "profession": "软件工程（卓越工程师班）"
            }, {
                "professionid": "50",
                "profession": "计算机科学与技术"
            }, {
                "professionid": "51",
                "profession": "软件工程"
            }, {
                "professionid": "52",
                "profession": "网络工程"
            }]
        }, {
            "collegeid": "15",
            "college": "材料与能源学院",
            "professions": [{
                "professionid": "86",
                "profession": "材料成型及控制工程（卓越工程师班）"
            }, {
                "professionid": "87",
                "profession": "材料类（创新班）"
            }, {
                "professionid": "88",
                "profession": "材料成型及控制工程"
            }, {
                "professionid": "89",
                "profession": "金属材料工程（金属材料制备及模具方向）"
            }, {
                "professionid": "90",
                "profession": "高分子材料与工程"
            }, {
                "professionid": "91",
                "profession": "能源与动力工程（热电工程方向）"
            }, {
                "professionid": "92",
                "profession": "能源与动力工程（制冷与空调方向）"
            }, {
                "professionid": "93",
                "profession": "电子科学与技术（电子信息材料及元器件方向）"
            }, {
                "professionid": "94",
                "profession": "微电子科学与工程"
            }]
        }, {
            "collegeid": "16",
            "college": "环境科学与工程学院",
            "professions": [{
                "professionid": "95",
                "profession": "环境工程"
            }, {
                "professionid": "96",
                "profession": "环境科学"
            }, {
                "professionid": "97",
                "profession": "生物工程（环境生物技术方向）"
            }, {
                "professionid": "98",
                "profession": "安全工程"
            }]
        }, {
            "collegeid": "8",
            "college": "外国语学院",
            "professions": [{
                "professionid": "53",
                "profession": "英语（翻译方向）"
            }, {
                "professionid": "54",
                "profession": "英语（科技方向）"
            }, {
                "professionid": "55",
                "profession": "商务英语"
            }, {
                "professionid": "56",
                "profession": "日语"
            }]
        }, {
            "collegeid": "17",
            "college": "应用数学学院",
            "professions": [{
                "professionid": "99",
                "profession": "信息与计算科学（信息计算方向）"
            }, {
                "professionid": "100",
                "profession": "信息与计算科学（信息安全方向）"
            }, {
                "professionid": "101",
                "profession": "应用统计学"
            }]
        }, {
            "collegeid": "9",
            "college": "物理与光电工程学院",
            "professions": [{
                "professionid": "57",
                "profession": "电子科学与技术(卓越工程师班)"
            }, {
                "professionid": "58",
                "profession": "电子科学与技术"
            }, {
                "professionid": "59",
                "profession": "光电信息科学与工程"
            }]
        }, {
            "collegeid": "10",
            "college": "艺术设计学院",
            "professions": [{
                "professionid": "60",
                "profession": "工业设计"
            }, {
                "professionid": "61",
                "profession": "产品设计"
            }, {
                "professionid": "62",
                "profession": "视觉传达设计"
            }, {
                "professionid": "63",
                "profession": "服装设计与工程"
            }, {
                "professionid": "64",
                "profession": "服装与服饰设计"
            }, {
                "professionid": "65",
                "profession": "服装与服饰设计（形象设计与服装表演方向）"
            }, {
                "professionid": "66",
                "profession": "环境设计"
            }, {
                "professionid": "67",
                "profession": "动画"
            }, {
                "professionid": "68",
                "profession": "数字媒体艺术"
            }, {
                "professionid": "69",
                "profession": "美术学"
            }]
        }, {
            "collegeid": "11",
            "college": "政法学院",
            "professions": [{
                "professionid": "70",
                "profession": "法学"
            }, {
                "professionid": "71",
                "profession": "社会工作"
            }, {
                "professionid": "72",
                "profession": "公共事业管理"
            }]
        }, {
            "collegeid": "12",
            "college": "建筑与城市规划学院",
            "professions": [{
                "professionid": "73",
                "profession": "建筑学"
            }, {
                "professionid": "74",
                "profession": "城乡规划"
            }, {
                "professionid": "75",
                "profession": "风景园林"
            }]
        }, {
            "collegeid": "13",
            "college": "经济与贸易学院",
            "professions": [{
                "professionid": "76",
                "profession": "金融工程"
            }, {
                "professionid": "77",
                "profession": "经济学"
            }, {
                "professionid": "78",
                "profession": "国际经济与贸易"
            }, {
                "professionid": "79",
                "profession": "会展经济与管理"
            }, {
                "professionid": "80",
                "profession": "投资学"
            }]
        }, {
            "collegeid": "14",
            "college": "商学院",
            "professions": [{
                "professionid": "81",
                "profession": "电子商务（三年制专科）"
            }, {
                "professionid": "82",
                "profession": "市场营销（三年制专科）"
            }, {
                "professionid": "83",
                "profession": "国际经济与贸易（三年制专科）"
            }, {
                "professionid": "84",
                "profession": "工商企业管理（三年制专科）"
            }, {
                "professionid": "85",
                "profession": "商务英语（三年制专科）"
            }]
        }]
    }
})